title: Partho Malakar # your name (or website title) here
logo: â€œ/myself.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="mailto:iamparthomalakar@gmail.com">iamparthomalakar@gmai.com </a>
  <br>
  <a href="https://www.linkedin.com/in/parthomalakar/">LinkedIn Profile</a>
  <br>

theme: jekyll-theme-minimal
